[package]
name = "Filesify"
description = "..."

repository = "https://github.com/moemannn/Filesify"
homepage = "https://github.com/moemannn/Filesify"

version = "0.0.1"
edition = "2024"

readme = "README.md"
authors = ["moemannn"]
license = "LICENSE"

[dependencies]
ratatui = { version = "0.30.0", default-features = false, features = ["crossterm"] }
